services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "80:80"

  postgres:
    image: "postgres:15.4"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      TZ: Asia/Tehran
    volumes:
      - postgresql:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgresql:
    driver: local
